# Generated by Django 6.0.1 on 2026-02-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_alter_course_owner_module_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Instructor', 'Instructor'), ('Student', 'Student')], default='Student', max_length=20),
        ),
    ]
