# Generated by Django 6.0.1 on 2026-02-16 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0006_alter_lesson_options_alter_user_role'),
        ('student', '0002_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('course_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_course', to='instructor.course')),
                ('user_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_course_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
